name: Emraors
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - hspec
  - QuickCheck
  - random >= 1.2.1.1
  - split 
  - transformers
  - mtl
  - containers
  - nonempty-containers
  - checkers
  - trifecta
  - parsers
  - raw-strings-qq
  - attoparsec
  - aeson
  - bytestring
  - hedis
  - network-uri
  - random
  - scotty
  - semigroups
  - text
  - tree-diff
  - lens >= 4.0

data-dir: data

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-top-binds

library:
  source-dirs:
    - chapter12
    - chapter13
    - chapter14
    - chapter15
    - chapter16
    - chapter17
    - chapter18
    - chapter19
    - chapter20
    - chapter21
    - chapter22
    - chapter23
    - chapter24
    - chapter25
