name:                chapter03
version:             0.1.0.0
github:              "nivox/haskellbook"
license:             BSD3
author:              "Andrea Zito"
maintainer:          "zito.andrea@gmail.com"
copyright:           "2022 Andrea Zito"

#extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nivox/haskellbook#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-type-defaults

executables:
  reverse:
    main: Reverse.hs
    source-dirs: src/
    ghc-options:
    - -main-is Reverse

library:
  source-dirs: src/
  exposed-modules:
  - Chapter03


tests:
  haskellbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter03
    - HUnit
    - QuickCheck
    - hspec
